version: '2'
services:
    elk:
        build: docker/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        environment:
            CONNEXION_STRING: ~
            CONNEXION_USER: ~
            CONNEXION_PWD: ~
            SSH_TUNNEL_USER: ~
            SSH_TUNNEL_HOST: ~
            SSH_AUTH_SOCK: /ssh-agent
            TRACKING_COLUMN: id
        volumes:
            - './queries:/queries'
            - '$SSH_AUTH_SOCK:/ssh-agent'