version: '2'
services:
    elk:
        build: docker/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        environment:
            CONNEXION_STRING: ~
            CONNEXION_USER: ~
            CONNEXION_PWD: ~
            SSH_TUNNEL_PORT: 22
            SSH_TUNNEL_USER: ~
            SSH_TUNNEL_HOST: ~
            SSH_TUNNEL_MYSQL_LOCAL_PORT: 1234
            SSH_TUNNEL_MYSQL_REMOTE_HOST: 127.0.0.1
            SSH_TUNNEL_MYSQL_REMOTE_PORT: 3306
            SSH_AUTH_SOCK: /ssh-agent
        volumes:
            - './queries:/root/statements'
            - '$SSH_AUTH_SOCK:/ssh-agent'
