version: '2'
services:
    elk:
        build: docker/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        volumes:
            - ./docker/elk/config:/opt/logstash/config/sql
            - ./queries:/opt/logstash/config/statements
        environment:
            CONNEXION_STRING: jdbc:mysql://172.18.0.9/cinefabrique
            CONNEXION_USER: cinefabrique
            CONNEXION_PWD: cinefabrique

networks:
    default:
        external:
            name: nginx-proxy