version: '2'
services:
    elk:
        build: docker/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
        volumes:
            - ./docker/elk/config:/opt/logstash/config/sql

networks:
    default:
        external:
            name: nginx-proxy